title: "NuFash"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S2-CS2103T-T12-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
