title: "FlashBack"
theme: minima
header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md
  - Testing.md

markdown: kramdown

repository: "AY2021S2-CS2103T-T13-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
