title: "BookCoin To The Moon"
theme: jekyll-theme-cayman

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S2-CS2103-W17-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
