title: "MeetBuddy"
theme: minima

header_pages:
  - UserGuide.md
  - AboutUs.md
  - DeveloperGuide.md

markdown: kramdown

repository: "AY2021S2-CS2103-T16-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
